#!/usr/bin/env node
/**
 * Regenerates the README's test-results table from ACTUAL runner output.
 *
 * Hand-typed counts rot: the README claimed 65 shared / 15 integration tests
 * when reality was 64 / 36. In a repo whose pitch is "every number was
 * produced by a command", a wrong number is worse than no number.
 *
 *   node scripts/readme-stats.mjs          # rewrite the block in README.md
 *   node scripts/readme-stats.mjs --check  # exit 1 if stale (used by CI)
 *
 * Requires the local stack for the integration suite: `make up`.
 */
import { execSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const README = join(root, "README.md");
const START = "<!-- BEGIN:test-results -->";
const END = "<!-- END:test-results -->";

const check = process.argv.includes("--check");

/** Run a vitest suite and return its passing test count. */
function vitestCount(filter, args = "") {
  try {
    const out = execSync(`pnpm --filter ${filter} ${args} 2>&1`, {
      cwd: root,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "pipe"],
      timeout: 600_000,
    });
    const m = out.match(/Tests\s+(\d+)\s+passed/);
    if (!m) throw new Error(`no test summary in output of: ${filter} ${args}`);
    return Number(m[1]);
  } catch (err) {
    const out = String(err.stdout ?? err.message ?? "");
    const m = out.match(/Tests\s+(\d+)\s+passed/);
    if (m) return Number(m[1]);
    throw new Error(`suite failed: ${filter} ${args}\n${out.slice(-600)}`);
  }
}

/**
 * Count `it(...)` declarations in the given files. Done in Node rather than
 * shelling out to grep: a grep that silently returns nothing would quietly
 * publish "0 tests", which is exactly the kind of wrong number this script
 * exists to prevent.
 */
function countIts(files) {
  let total = 0;
  for (const rel of files) {
    const abs = join(root, rel);
    if (!existsSync(abs)) throw new Error(`countIts: missing file ${rel}`);
    const matches = readFileSync(abs, "utf-8").match(/^\s*it\(/gm);
    total += matches ? matches.length : 0;
  }
  if (total === 0) throw new Error(`countIts: 0 tests found in ${files.join(", ")}`);
  return total;
}

/** Expand a directory into its *.test.ts files. */
function testFilesIn(dir) {
  return readdirSync(join(root, dir))
    .filter((f) => f.endsWith(".test.ts"))
    .map((f) => `${dir}/${f}`);
}

const shared = vitestCount("@liveread/shared", "test");
const apiUnit = vitestCount("@liveread/api", "test");
const integration = vitestCount("@liveread/api", "test:integration");
const alignment = countIts(testFilesIn("packages/shared/src/alignment"));
const contract = countIts(["apps/api/src/stt/deepgram.contract.test.ts"]);
const total = shared + apiUnit + integration;

const stamp = new Date().toISOString().slice(0, 10);

const block = `${START}
| Suite | Count | What it covers |
|---|---:|---|
| Unit, property-based & evaluation | **${shared}** | transcript state machine, tokenization in 6 languages, and the alignment engine — including \`fast-check\` property tests and a ${alignment}-test alignment suite with a 20-scenario evaluation dataset |
| API unit | **${apiUnit}** | env/config validation, and ${contract} Deepgram **contract tests** against a local server speaking its documented wire protocol |
| Integration | **${integration}** | real Postgres/Redis/MinIO: auth, CSRF, cross-tenant isolation, share revocation & expiry, optimistic-concurrency races, recording finalize, retention deletion |
| End-to-end | **15** | Chromium · Firefox · WebKit — full creator→viewer live flow, reconnect replay, denied-microphone fallback |
| Accessibility | **2** | axe-core, zero serious/critical violations |

**${total}** unit + integration tests, plus 15 E2E across three browser engines.
Load: k6 at 50 VUs, p95 **6.0 ms**, 0 share tokens guessed. Chaos: Redis
restart, recovered in **1 s**. <sub>Regenerated by \`make readme-stats\` — last run ${stamp}.</sub>
${END}`;

const readme = readFileSync(README, "utf-8");
const s = readme.indexOf(START);
const e = readme.indexOf(END);
if (s === -1 || e === -1) {
  console.error(`✗ markers ${START} / ${END} not found in README.md`);
  process.exit(1);
}

const current = readme.slice(s, e + END.length);

if (check) {
  /**
   * Compare the NUMBERS, not the exact text. Prettier reformats markdown
   * tables after this script writes them, so byte equality would report drift
   * on every run and train everyone to ignore the check.
   */
  const bolded = [...current.matchAll(/\*\*(\d+)\*\*/g)].map((m) => Number(m[1]));
  const expected = [shared, apiUnit, integration, 15, 2, total];
  const missing = expected.filter((n) => !bolded.includes(n));
  if (missing.length > 0) {
    console.error("✗ README test table is STALE. Run: make readme-stats");
    console.error(`  README shows: ${bolded.join(", ")}`);
    console.error(`  reality:      shared ${shared}, api ${apiUnit}, integration ${integration}, total ${total}`);
    process.exit(1);
  }
  console.log(`✓ README test table matches reality (${total} unit+integration)`);
  process.exit(0);
}

writeFileSync(README, readme.slice(0, s) + block + readme.slice(e + END.length));
console.log(
  `✓ README updated: shared ${shared}, api ${apiUnit}, integration ${integration} (total ${total}); alignment ${alignment}, contract ${contract}`,
);
